### PR TITLE
contact.html

### PR DESCRIPTION
**Pull request by AniruddhaTayade123**
Added links for address, telephone and e-mail.

### CODE REVIEW

**Review by gabhijit — COMMENTED** [review]
@AniruddhaTayade123 -- These are intentionally kept as not hyperlink-able. Hence we've not added links there originally, so these changes don't make sense. 

Hope it helps

**Comment by AniruddhaTayade123** [comment]
Okay, I see. Thank you for the response.

**Comment by gabhijit** [comment]
@AniruddhaTayade123 : I see there were a couple of issues created by @mayurhyphenOs , I was not aware of that. Those issues are closed right now.

**Comment by gabhijit** [comment]
#21 #22 (closed)

**Pull request closed without merging**
